### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by HugoPu** [hadifar/stc_clustering#1]
In data_loader.py `all_lines = inp_txt.readlines()[:-1]` 
Why do not use the last sentence?

**Comment by hadifar** [comment]
The last line is a line-break so we don't need it.

**Comment by HugoPu** [comment]
When I use the code `load_stackoverflow` to read [data file](https://github.com/hadifar/stc_clustering/tree/master/data/stackoverflow), it has 20000 lines, the last line is not line-break, it is `Magento : Call to a member function count() on a non-object`.
![image](https://user-images.githubusercontent.com/22905948/66901273-f6ba1f00-f030-11e9-947a-426dc2981220.png)
![image](https://user-images.githubusercontent.com/22905948/66901183-ca060780-f030-11e9-9c53-1f1903a60a3a.png)
 And when it reads the labels, 20000 lines are read, so I think the embedding of last instance is wrong.
```
    with open(data_path + 'label_StackOverflow.txt') as label_file:
        y = np.array(list((map(int, label_file.readlines()))))
```
![image](https://user-images.githubusercontent.com/22905948/66901394-3254e900-f031-11e9-9f3c-e23f49992bfe.png)

**Comment by 425776024** [comment]
> When I use the code `load_stackoverflow` to read [data file](https://github.com/hadifar/stc_clustering/tree/master/data/stackoverflow), it has 20000 lines, the last line is not line-break, it is `Magento : Call to a member function count() on a non-object`.
> ![image](https://user-images.githubusercontent.com/22905948/66901273-f6ba1f00-f030-11e9-947a-426dc2981220.png)
> ![image](https://user-images.githubusercontent.com/22905948/66901183-ca060780-f030-11e9-9c53-1f1903a60a3a.png)
> And when it reads the labels, 20000 lines are read, so I think the embedding of last instance is wrong.
> 
> ```
>     with open(data_path + 'label_StackOverflow.txt') as label_file:
>         y = np.array(list((map(int, label_file.readlines()))))
> ```
> 
> ![image](https://user-images.githubusercontent.com/22905948/66901394-3254e900-f031-11e9-9f3c-e23f49992bfe.png)

我同样遇到这个问题，请问你最后怎么处理？我也感觉作者这个代码有问题
