### ISSUE TITLE
how to choose hypoparameters

### ISSUE THREAD

**Issue by Nipi64310** [hadifar/stc_clustering#2]
three datasets have different hypoparameters.
after run the code in my corpus(text size is 5w and y is none. init n_cluster=150)
when i use stackoverflow params,  got same cluster id for all questions.
when i use search_snippets params, got 150 clusters. but the result is very bad.

i increase batch_size -> 256, decrease update_interval -> 40,  get more better result.

so how to choose hypoparameters  on a new corpus.

**Comment by hadifar** [comment]
Hi @Nipi64310, thanks for your interest.
Can I ask you what do you mean by text size is **5w**? The model is sensitive to hyperparameters but you might have an intuition about the hyperparameters based on your text length, number of clusters, clusters distribution, and etc. To be honest, I tried the model with a different corpus where number of clusters was about 40-50, and I didn't get a good result.

**Comment by Nipi64310** [comment]
> Hi @Nipi64310, thanks for your interest.
> Can I ask you what do you mean by text size is **5w**? The model is sensitive to hyperparameters but you might have an intuition about the hyperparameters based on your text length, number of clusters, clusters distribution, and etc. To be honest, I tried the model with a different corpus where number of clusters was about 40-50, and I didn't get a good result.

hi @hadifar,  thanks for your reply.  I want to do a intent classification task and cluster for define intent classification label, text size is  5w means my corpus have 50000 rows, text length about 16 [95% row text length below 16]. I spent a lot of time tune the parameters and got a good result at last, but i still confused in parameters choose in a new corpus.
