### ISSUE TITLE
Code for visualization

### ISSUE THREAD

**Issue by ans92** [hadifar/stc_clustering#5]
Hi @hadifar,
Thank you for your useful code. I want to say that can you please also share code for visualization of final clusters as shown in research paper. I want to run your code on my data set and also want to see visualization of my clusters. If you have time can you please share clusters visualization code with me. Thank you.

**Comment by hadifar** [comment]
Sorry for the late reply you can find the code for visualization in the following gist (It is not clean though):
https://gist.github.com/hadifar/0ad14d51334f38e50977d91974ba73ac
