### ISSUE TITLE
Run code on my data set

### ISSUE THREAD

**Issue by ans92** [hadifar/stc_clustering#6]
Hi @hadifar ,
Thank you for great code. I want to run this code with my data set. There are 6 files in stackoverflow data folder. 
1. label_StackOverflow.txt
2. StackOverflow.mat
3. title_StackOverflow.txt
4. vocab_emb_Word2vec_48_index.dic
5. vocab_emb_Word2vec_48.vec
6. vocab_withIdx.dic

Now in order to run your code with my data set I need my own label_StackOverflow.txt file and title_StackOverflow.txt file. As I will do this with python so shall I also need StackOverflow.mat file. If yes then how can I develop one for my data set. 

There are other three files: vocab_emb_Word2vec_48_index.dic, vocab_emb_Word2vec_48.vec and vocab_withIdx.dic. Please guide me how can I produce above three files from my data set. I look forward for your response. Thank you for your help.

**Comment by GuanYingxuan** [comment]
I have the same question. Did you solve it?

**Comment by GuanYingxuan** [comment]
> Hi @hadifar , Thank you for great code. I want to run this code with my data set. There are 6 files in stackoverflow data folder.
> 
> 1. label_StackOverflow.txt
> 2. StackOverflow.mat
> 3. title_StackOverflow.txt
> 4. vocab_emb_Word2vec_48_index.dic
> 5. vocab_emb_Word2vec_48.vec
> 6. vocab_withIdx.dic
> 
> Now in order to run your code with my data set I need my own label_StackOverflow.txt file and title_StackOverflow.txt file. As I will do this with python so shall I also need StackOverflow.mat file. If yes then how can I develop one for my data set.
> 
> There are other three files: vocab_emb_Word2vec_48_index.dic, vocab_emb_Word2vec_48.vec and vocab_withIdx.dic. Please guide me how can I produce above three files from my data set. I look forward for your response. Thank you for your help.

I have the same question. Did you solve it?

**Comment by hadifar** [comment]
Thanks for your interest in our work. You can train your own word vectors (e.g., use [gensim](https://radimrehurek.com/gensim/models/word2vec.html)) and extract the mentioned information by iterating through the output file. For instance, `vocab_emb_Word2vec_48_index.vec` can be obtained by `model.wv`.

**Comment by GuanYingxuan** [comment]
> Thanks for your interest in our work. You can train your own word vectors (e.g., use [gensim](https://radimrehurek.com/gensim/models/word2vec.html)) and extract the mentioned information by iterating through the output file. For instance, `vocab_emb_Word2vec_48_index.vec` can be obtained by `model.wv`.

Thank you very much! I have successfully run my code according to your method.
